CREATE TABLE PERSON (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    PRIMARY KEY(ID)
);

INSERT INTO PERSON(FIRST_NAME, LAST_NAME)
VALUES ('JOHN', 'ATOS');

INSERT INTO PERSON(FIRST_NAME, LAST_NAME)
VALUES ('JEFF', 'ATOS');

INSERT INTO PERSON(FIRST_NAME, LAST_NAME)
VALUES ('BOB', 'AUSTIN');

INSERT INTO PERSON(FIRST_NAME, LAST_NAME)
VALUES ('BOB', 'BEEP');

INSERT INTO PERSON(FIRST_NAME, LAST_NAME)
VALUES ('GABRIEL', 'GRABSKI');